language: node_js
node_js: stable
branches:
  only:
    - master
script:
  - npm install
  - npm run build
after_success:
  - cd dist
  - git init
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
env:
  global:
    - GH_REF: github.com/WQone/vue-element-demo.git
